//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ACE400Cal.rc
//
#define IDC_BUTTON_Config               2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MANUAL_TEST_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_MAIN_DIALOG                 131
#define IDD_CALIB_DIALOG                132
#define IDD_CONFIG_DIALOG               134
#define IDD_DIALOG_NUM_PAD              160
#define IDD_DIALOG_CONTROLLER           277
#define IDC_LABEL1                      1000
#define IDC_STATIC_I_ADC                1001
#define IDC_STATIC_I_MNT                1002
#define IDC_STATIC_I_MNT_AD             1003
#define IDC_EDIT_LV1                    1007
#define IDC_SSPANEL2                    1007
#define IDC_EDIT_LV2                    1008
#define IDC_SSPANEL4                    1008
#define IDC_EDIT_HV1                    1009
#define IDC_EDIT_BPOINT_CC_V            1010
#define IDC_EDIT_SPARK                  1011
#define IDC_EDIT_HV2                    1012
#define IDC_BUTTON_LV1_SET              1013
#define IDC_BUTTON_LV2_SET              1014
#define IDC_BUTTON_DEL                  1014
#define IDC_BUTTON_HV1_SET              1015
#define IDC_BUTTON_HV2_SET              1016
#define IDC_BUTTON_CURSOR_BACK          1016
#define IDC_RADIO_LV1                   1017
#define IDC_BUTTON_CURSOR_FWD           1017
#define IDC_RADIO_I_RNG0                1018
#define IDC_BUTTON_BACKSPACE            1018
#define IDC_BUTTON_I_SET                1019
#define IDC_BUTTON_KEYPAD_7             1019
#define IDC_BUTTON_KEYPAD_8             1020
#define IDC_RADIO_4WGAIN_S1000          1020
#define IDC_BUTTON_AD_READ              1021
#define IDC_BUTTON_KEYPAD_9             1021
#define IDC_RADIO_LV2                   1022
#define IDC_BUTTON_CLR                  1022
#define IDC_RADIO_HV1                   1023
#define IDC_BUTTON_KEYPAD_4             1023
#define IDC_RADIO_HV2                   1024
#define IDC_BUTTON_KEYPAD_5             1024
#define IDC_BUTTON_KEYPAD_6             1025
#define IDC_RADIO_HVO_GAIN1             1025
#define IDC_EDIT_I                      1026
#define IDC_BUTTON_CANCEL               1026
#define IDC_RADIO_I_RNG1                1027
#define IDC_BUTTON_KEYPAD_1             1027
#define IDC_RADIO_I_RNG2                1028
#define IDC_BUTTON_KEYPAD_2             1028
#define IDC_RADIO_I_RNG3                1029
#define IDC_SSPANEL3                    1029
#define IDC_RADIO_I_RNG4                1030
#define IDC_BUTTON_KEYPAD_3             1030
#define IDC_BUTTON_ENTER                1031
#define IDC_RADIO_4WGAIN_F10            1031
#define IDC_BUTTON_SIGN                 1032
#define IDC_RADIO_4WGAIN_F100           1032
#define IDC_BUTTON_KEYPAD_0             1033
#define IDC_RADIO_4WGAIN_F1000          1033
#define IDC_BUTTON_DOT                  1034
#define IDC_RADIO_HVO_GAIN2             1034
#define IDC_RADIO_HVO_GAIN3             1035
#define IDC_RADIO_HVO_GAIN4             1036
#define IDC_BUTTON_BPOINT_CCV_SET       1037
#define IDC_LIST_CPOINT                 1038
#define IDC_BUTTON_CPOINT_CCV_SET       1039
#define IDC_RADIO_HVC                   1040
#define IDC_RADIO_I_RNG6                1041
#define IDC_RADIO_PULSE                 1042
#define IDC_EDIT_LV1_DA                 1043
#define IDC_BUTTON_SPARK_SET            1044
#define IDC_EDIT_CPOINT_CC_V            1045
#define IDC_RADIO_PULSE_MEASURE_CAV0    1046
#define IDC_RADIO_PULSE_MEASURE_CAV1    1047
#define IDC_RADIO_PULSE_MEASURE_CAV2    1048
#define IDC_RADIO_PULSE_MEASURE_CAV3    1049
#define IDC_EDIT_LV2_DA                 1050
#define IDC_EDIT_HV1_DA                 1051
#define IDC_EDIT_HV2_DA                 1052
#define IDC_BUTTON_INIT                 1053
#define IDC_EDIT_SPARK_DA               1054
#define IDC_RADIO_LVC                   1055
#define IDC_RADIO_I_CC                  1056
#define IDC_RADIO_I_CV                  1057
#define IDC_RADIO_BPOINT_CV             1058
#define IDC_RADIO_VCSFT                 1059
#define IDC_RADIO_VBFT                  1060
#define IDC_RADIO_PFT_FAST              1061
#define IDC_RADIO_PFT_SLOW              1062
#define IDC_RADIO_BPOINT_CC             1063
#define IDC_RADIO_CPOINT_CV             1064
#define IDC_RADIO_CPOINT_CC             1065
#define IDC_BUTTON_VB_RST_ALL           1066
#define IDC_BUTTON_VC_RST_ALL           1067
#define IDC_SSPANEL1                    1068
#define IDC_BUTTON_Calib                1069
#define IDC_EDIT_CPOINT_TR              1070
#define IDC_BUTTON_ManualTest           1070
#define IDC_BUTTON_CPOINT_TR_SET        1071
#define IDC_GRID_CAL_RESULT             1071
#define IDC_RADIO_CBOXA                 1072
#define IDC_COMBO_CALIB_MODE            1072
#define IDC_RADIO_CBOXB                 1073
#define IDC_EDIT_MEAS_CNT               1073
#define IDC_RADIO_CBOXC                 1074
#define IDC_GRID_CONDITION              1074
#define IDC_RADIO_CBOXD                 1075
#define IDC_BUTTON_LOAD_REF             1075
#define IDC_RADIO_CBOXE                 1076
#define IDC_BUTTON_START_MEAS           1076
#define IDC_RADIO_CBOXF                 1077
#define IDC_BUTTON_CHG_REF              1077
#define IDC_RADIO_CBOXG                 1078
#define IDC_BUTTON_SAVE_REF             1078
#define IDC_RADIO_CBOXH                 1079
#define IDC_BUTTON_CLR_SCREEN           1079
#define IDC_EDIT_CPOINT_RY              1080
#define IDC_BUTTON_STOP_MEAS            1080
#define IDC_BUTTON_CPOINT_RY_SET        1081
#define IDC_BUTTON_VIEW_RESULT_FILE     1081
#define IDC_BUTTON_AUTO_CALIB           1082
#define IDC_BUTTON_SAVE_CONDITION       1083
#define IDC_RADIO_CCPLD0                1084
#define IDC_BUTTON_VIEW_CONDITION_FILE  1084
#define IDC_RADIO_CCPLD1                1085
#define IDC_CHECK_PRT_BASIC             1085
#define IDC_RADIO_CCPLD2                1086
#define IDC_CHECK_PRT_LEVEL1            1086
#define IDC_RADIO_CCPLD3                1087
#define IDC_CHECK_PRT_Level2            1087
#define IDC_CHECK_PRT_LEVEL3            1088
#define IDC_CHECK_PRT_DEVICE            1089
#define IDC_CHECK_PRT_DEV_D64           1090
#define IDC_STATIC_PRINT_STATE          1091
#define IDC_BUTTON_CPOINT_TR_RST        1094
#define IDC_SSPANEL_NUM_DATA            1096
#define IDC_BUTTON_POINT_SET            1098
#define IDC_LABEL_I_AMP                 1099
#define IDC_BUTTON_BOX_RST              1100
#define IDC_LABEL_V_VOLT                1101
#define IDC_LABEL_R_OHM                 1102
#define IDC_BUTTON_VB_OUT_SET           1103
#define IDC_BUTTON_CPOINT_RY_RST        1104
#define IDC_LIST_MSG                    1111
#define IDC_STATIC_LV1                  1112
#define IDC_SSPANEL_MIN_VALUE           1115
#define IDC_SSPANEL_NUMPOS_0            1116
#define IDC_SSPANEL_NUMPOS_1            1117
#define IDC_SSPANEL_NUMPOS_2            1118
#define IDC_EDIT_CPIN                   1119
#define IDC_SSPANEL_NUMPOS_3            1119
#define IDC_CHECK_CPIN0                 1120
#define IDC_SSPANEL_NUMPOS_4            1120
#define IDC_CHECK_CPIN1                 1121
#define IDC_SSPANEL_NUMPOS_5            1121
#define IDC_CHECK_CPIN2                 1122
#define IDC_SSPANEL_NUMPOS_6            1122
#define IDC_CHECK_CPIN3                 1123
#define IDC_SSPANEL_NUMPOS_7            1123
#define IDC_CHECK_CPIN4                 1124
#define IDC_SSPANEL_NUMPOS_8            1124
#define IDC_CHECK_CPIN5                 1125
#define IDC_SSPANEL_NUMPOS_9            1125
#define IDC_SSPANEL_NUMPOS_10           1126
#define IDC_SSPANEL_NUMPOS_11           1127
#define IDC_SSPANEL_MAX_VALUE           1128
#define IDC_STATIC_LV1_MNT              1131
#define IDC_STATIC_LV2_MNT              1132
#define IDC_CHECK_CPCB0                 1133
#define IDC_CHECK_CPCB1                 1134
#define IDC_CHECK_CPCB2                 1135
#define IDC_CHECK_CPCB3                 1136
#define IDC_EDIT_BPOINT_TR              1137
#define IDC_BUTTON_BPOINT_TR_SET        1138
#define IDC_RADIO_BBOXA                 1139
#define IDC_RADIO_BBOXB                 1140
#define IDC_RADIO_BBOXC                 1141
#define IDC_RADIO_BBOXD                 1142
#define IDC_RADIO_BBOXE                 1143
#define IDC_RADIO_BBOXF                 1144
#define IDC_RADIO_BBOXG                 1145
#define IDC_RADIO_BBOXH                 1146
#define IDC_RADIO_BCPLD0                1147
#define IDC_RADIO_BCPLD1                1148
#define IDC_RADIO_BCPLD2                1149
#define IDC_RADIO_BCPLD3                1150
#define IDC_BUTTON_BPOINT_RY_RST        1151
#define IDC_STATIC_LV1_MNT_AD           1152
#define IDC_STATIC_LV2_MNT_AD           1153
#define IDC_EDIT_BPIN                   1154
#define IDC_STATIC_HV1_MNT              1155
#define IDC_CHECK_BPIN0                 1156
#define IDC_CHECK_BPIN1                 1157
#define IDC_CHECK_BPIN2                 1158
#define IDC_CHECK_BPIN3                 1159
#define IDC_CHECK_BPIN4                 1160
#define IDC_CHECK_BPIN5                 1161
#define IDC_CHECK_BPCB0                 1162
#define IDC_CHECK_BPCB1                 1163
#define IDC_CHECK_BPCB2                 1164
#define IDC_CHECK_BPCB3                 1165
#define IDC_STATIC_HV2_MNT              1166
#define IDC_STATIC_HV1_MNT_AD           1167
#define IDC_STATIC_LV1_UNIT1            1168
#define IDC_STATIC_HV2_MNT_AD           1168
#define IDC_STATIC_LV2_UNIT1            1169
#define IDC_STATIC_HV1_UNIT1            1170
#define IDC_STATIC_HV2_UNIT1            1171
#define IDC_RADIO_IFFT                  1173
#define IDC_RADIO_ISFT                  1174
#define IDC_RADIO_VCFFT                 1176
#define IDC_RADIO_FWFT                  1177
#define IDC_BUTTON_BREAK                1178
#define IDC_BUTTON_BPOINT_RY_SET        1179
#define IDC_BUTTON_BPOINT_TR_RST        1180
#define IDC_STATIC_SPARK_UNIT           1182
#define IDC_STATIC_VB_OUT_MNT           1183
#define IDC_STATIC_VB_OUT_MNT_AD        1184
#define IDC_LIST_BPOINT                 1191
#define IDC_STATIC_I_UNIT               1192
#define IDC_RADIO_BPCB_ENABLE0          1193
#define IDC_RADIO_BPCB_ENABLE1          1194
#define IDC_RADIO_CPCB_ENABLE0          1195
#define IDC_RADIO_CPCB_ENABLE1          1196
#define IDC_STATIC_I                    1197
#define IDC_STATIC_V                    1198
#define IDC_STATIC_R                    1199
#define IDC_STATIC_QM_I_UNIT            1200
#define IDC_STATIC_QM_V_UNIT            1201
#define IDC_STATIC_QM_R_UNIT            1202
#define IDC_STATIC_QM_I_ADVALUE         1203
#define IDC_STATIC_QM_V_ADVALUE         1204
#define IDC_EDIT_QM_BPOINT              1205
#define IDC_EDIT_QM_CPOINT              1206
#define IDC_STATIC_VB_OUT_UNIT          1207
#define IDC_STATIC_I_UNIT2              1207
#define IDC_EDIT_BPOINT_RY              1209
#define IDC_CHECK_I_HIGH_GAIN           1211
#define IDC_CHECK_SPARK_ON              1226
#define IDC_CHECK_DC_OUT                1229
#define IDC_CHECK_VB_GUARD_ON           1231
#define IDC_CHECK_VC_GUARD_ON           1232
#define IDC_STATIC_BTR                  1233
#define IDC_STATIC_BRY                  1234
#define IDC_STATIC_CTR                  1235
#define IDC_STATIC_CRY                  1236
#define IDC_CHECK_PULSE                 1237
#define IDC_STATIC_PULSE                1238
#define IDC_RADIO_PULSE_VOLT            1279
#define IDC_RADIO_HVOFT                 1281
#define IDC_RADIO_PULSE_VOLT1           1282
#define IDC_RADIO_PULSE_VOLT2           1283
#define IDC_RADIO_PULSE_VOLT3           1284
#define IDC_RADIO_PULSE_FREQ            1285
#define IDC_RADIO_PULSE_FREQ1           1286
#define IDC_RADIO_PULSE_FREQ2           1287
#define IDC_RADIO_PULSE_FREQ3           1288

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
