#if !defined(AFX_SSPNCTRL_H__317B7428_E7D1_4FD1_BF39_BC98618EBD61__INCLUDED_)
#define AFX_SSPNCTRL_H__317B7428_E7D1_4FD1_BF39_BC98618EBD61__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CSSPNCtrl wrapper class

class CSSPNCtrl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSSPNCtrl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xba686b9, 0xf7d3, 0x101a, { 0x99, 0x3e, 0x0, 0x0, 0xc0, 0xef, 0x6f, 0x5e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetCaption();
	void SetCaption(LPCTSTR);
	short GetBevelWidth();
	void SetBevelWidth(short);
	short GetBorderWidth();
	void SetBorderWidth(short);
	long GetBevelOuter();
	void SetBevelOuter(long);
	long GetBevelInner();
	void SetBevelInner(long);
	BOOL GetRoundedCorners();
	void SetRoundedCorners(BOOL);
	BOOL GetOutline();
	void SetOutline(BOOL);
	long GetFloodType();
	void SetFloodType(long);
	unsigned long GetFloodColor();
	void SetFloodColor(unsigned long);
	short GetFloodPercent();
	void SetFloodPercent(short);
	long GetShadowColor();
	void SetShadowColor(long);
	BOOL GetFloodShowPct();
	void SetFloodShowPct(BOOL);
	long GetFont3D();
	void SetFont3D(long);
	long GetAlignment();
	void SetAlignment(long);
	long GetAutoSize();
	void SetAutoSize(long);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	long GetMousePointer();
	void SetMousePointer(long);
	CPicture GetMouseIcon();
	void SetMouseIcon(LPDISPATCH);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);

// Operations
public:
	void Refresh();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SSPNCTRL_H__317B7428_E7D1_4FD1_BF39_BC98618EBD61__INCLUDED_)
